# THIS PART IS SOLELY FOR TRAINING PUROSES
# VISUALIZATION IS NOT AVAILIABLE ON EXPANSE SDSC

# Initialization of Geant4
/run/initialize

# Initialize Graphics Window
/vis/open OGL 600x600-0+0

# View from vector <1, 1, 1>
/vis/viewer/set/viewpointVector 1 1 1

# Other features to use
/vis/viewer/set/autorRefresh true

/vis/drawVolume

/vis/scene/add/trajectories smooth

/vis/scene/endOfEventAction accumulate

/vis/scene/scale 10 cm

/vis/scene/add/axes

/vis/scene/add/eventID